Repository TeamFILL-IN/Fill-iOS, pull requests merged in 2022-03, with the labels that each got.

#123 🔨[FIX] #121 - 스튜디오맵뷰 현상소 아이콘 변경, 초기위치 변경
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/icnStudio.imageset/Contents.json
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/icnStudio.imageset/icnStudio.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/icnStudio.imageset/icnStudio@2x.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/icnStudio.imageset/icnStudio@3x.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/icnStudioSelected.imageset/Contents.json
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/icnStudioSelected.imageset/icnStudioSelected.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/icnStudioSelected.imageset/icnStudioSelected@2x.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/icnStudioSelected.imageset/icnStudioSelected@3x.png
  Fillin-iOS/Fillin-iOS/Resources/Constants/Assets+Generated.swift
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapBottomSheetViewController/StudioMapContentViewController/StudioMapContentViewController.swift
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
Labels: FEAT, 주민 🥕

#122 [FEAT] #118 - OnboardingVC 릴리즈용 수정 완료
  Fillin-iOS/Fillin-iOS.xcodeproj/project.pbxproj
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/imgtrashRed.imageset/Contents.json
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/imgtrashRed.imageset/imgtrashRed.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/imgtrashRed.imageset/imgtrashRed@2x.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/imgtrashRed.imageset/imgtrashRed@3x.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/intro1.imageset/Contents.json
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/intro1.imageset/intro1.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/intro1.imageset/intro1@2x.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/intro1.imageset/intro1@3x.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/intro2.imageset/Contents.json
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/intro2.imageset/intro2.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/intro2.imageset/intro2@2x.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/intro2.imageset/intro2@3x.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/intro3.imageset/Contents.json
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/intro3.imageset/intro3.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/intro3.imageset/intro3@2x.png
  Fillin-iOS/Fillin-iOS/Resources/Assets/Assets.xcassets/intro3.imageset/intro3@3x.png
  Fillin-iOS/Fillin-iOS/Resources/Constants/Assets+Generated.swift
  Fillin-iOS/Fillin-iOS/Sources/SceneDelegate.swift
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/AddPhotoPopUpViewController/FirstAddPhotoPopUpViewController.swift
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/AddPhotoPopUpViewController/SecondAddPhotoPopUpViewController.swift
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/OnboardingViewController/Cell/OnboardingCollectionViewCell.swift
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/OnboardingViewController/DataModel/OnboardingDataModel.swift
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/OnboardingViewController/OnboardingFirstViewController.swift
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/OnboardingViewController/OnboardingSecondViewController.swift
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/OnboardingViewController/OnboardingThirdViewController.swift
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/OnboardingViewController/OnboardingViewController.swift
Labels: FEAT, DEL, 지수 👸🏻

#128 🔨[FIX] #125 - 바텀시트의 현상소 상세정보 부분 변경
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapBottomSheetViewController/StudioMapContentViewController/StudioMapContentViewController.swift
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
Labels: FIX, 주민 🥕

#130 🔨[FIX] #129 - 지도뷰 현상소 마커 중복클릭 방지
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/SplashViewController/SplashViewController.swift
  Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
Labels: FIX, 주민 🥕
